version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000" 
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - FRONTEND_URL=${FRONTEND_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - PORT=3000
    networks:
      - scholarbee-network
    restart: unless-stopped

networks:
  scholarbee-network:
    driver: bridge 